<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="analysisMetaModel"
    nsURI="platform:/resource/Kieker/model/AnalysisMetaModel.ecore" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="#//Configurable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurables" upperBound="-1"
        eType="#//Configurable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plugin" abstract="true" eSuperTypes="#//Configurable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPorts" upperBound="-1"
        eType="#//OutputPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dstInputPort" lowerBound="1"
        eType="#//InputPort" eOpposite="#//InputPort/inConnector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sicOutputPort" lowerBound="1"
        eType="#//OutputPort" eOpposite="#//OutputPort/outConnector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configurable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventTypes" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inConnector" upperBound="-1"
        eType="#//Connector" eOpposite="#//Connector/dstInputPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outConnector" upperBound="-1"
        eType="#//Connector" containment="true" eOpposite="#//Connector/sicOutputPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisPlugin" eSuperTypes="#//Plugin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPorts" upperBound="-1"
        eType="#//InputPort" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reader" eSuperTypes="#//Plugin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
