//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.01 at 08:06:02 AM CEST 
//


package org.graphdrawing.graphml.xmlns;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for graph.order.type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="graph.order.type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="free"/>
 *     &lt;enumeration value="nodesfirst"/>
 *     &lt;enumeration value="adjacencylist"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "graph.order.type")
@XmlEnum
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2014-04-01T08:06:02+02:00", comments = "JAXB RI v2.2.4-2")
public enum GraphOrderType {

    @XmlEnumValue("free")
    FREE("free"),
    @XmlEnumValue("nodesfirst")
    NODESFIRST("nodesfirst"),
    @XmlEnumValue("adjacencylist")
    ADJACENCYLIST("adjacencylist");
    private final String value;

    GraphOrderType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GraphOrderType fromValue(String v) {
        for (GraphOrderType c: GraphOrderType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
