//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 12:10:48 PM CET 
//

package org.graphdrawing.graphml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for key.for.type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="key.for.type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="all"/>
 *     &lt;enumeration value="graphml"/>
 *     &lt;enumeration value="graph"/>
 *     &lt;enumeration value="node"/>
 *     &lt;enumeration value="edge"/>
 *     &lt;enumeration value="hyperedge"/>
 *     &lt;enumeration value="port"/>
 *     &lt;enumeration value="endpoint"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "key.for.type")
@XmlEnum
public enum KeyForType {

	@XmlEnumValue("all")
	ALL("all"), @XmlEnumValue("graphml")
	GRAPHML("graphml"), @XmlEnumValue("graph")
	GRAPH("graph"), @XmlEnumValue("node")
	NODE("node"), @XmlEnumValue("edge")
	EDGE("edge"), @XmlEnumValue("hyperedge")
	HYPEREDGE("hyperedge"), @XmlEnumValue("port")
	PORT("port"), @XmlEnumValue("endpoint")
	ENDPOINT("endpoint");

	private final String value;

	KeyForType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static KeyForType fromValue(String v) {
		for (KeyForType c : KeyForType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
