name: Integration Test Execution (Regular)

on: [push, workflow_dispatch]

jobs:
  build:
    strategy: 
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          java: [ 11, 17, 21 ]
        fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} OS ${{ matrix.os }} sample
    steps:
    - name: Set Git Property and output path
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          git config --system core.longpaths true
        fi
      shell: bash
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build Kieker fully
      run: ./gradlew clean assemble mainJar aspectJJar -x check -x test
    - name: Execute integration tests
      run: ./gradlew monitoring:jarIntegrationTest -x check -x test
