<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="analysisMetaModel" nsURI="platform:/resource/Kieker/model/AnalysisMetaModel.ecore"
    nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plugins" upperBound="-1"
        eType="#//Plugin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositories" upperBound="-1"
        eType="#//Repository" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Dependency" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//View" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plugin" abstract="true" eSuperTypes="#//AnalysisComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositories" upperBound="-1"
        eType="#//RepositoryConnector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPorts" upperBound="-1"
        eType="#//OutputPort" containment="true" eOpposite="#//OutputPort/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displays" upperBound="-1"
        eType="#//Display" containment="true" eOpposite="#//Display/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventTypes" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//Filter" eOpposite="#//Filter/inputPorts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscribers" upperBound="-1"
        eType="#//InputPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//Plugin" eOpposite="#//Plugin/outputPorts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filter" eSuperTypes="#//Plugin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPorts" upperBound="-1"
        eType="#//InputPort" containment="true" eOpposite="#//InputPort/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reader" eSuperTypes="#//Plugin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Repository" eSuperTypes="#//AnalysisComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filePath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryConnector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" lowerBound="1"
        eType="#//Repository"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Display">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//Plugin" eOpposite="#//Plugin/displays"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayConnectors" upperBound="-1"
        eType="#//DisplayConnector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisplayConnector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="display" lowerBound="1"
        eType="#//Display"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisComponent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
</ecore:EPackage>
